//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSQLSmellSCA {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TSQLSmellSCA.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create ResourceManager for {0} from {1}..
        /// </summary>
        internal static string CannotCreateResourceManager {
            get {
                return ResourceManager.GetString("CannotCreateResourceManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSQLSmellSCA.Resources.
        /// </summary>
        internal static string ResourceBaseName {
            get {
                return ResourceManager.GetString("ResourceBaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid cross server joins.
        /// </summary>
        internal static string TSQLSmell_RuleName01 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best practice is to use two part naming.
        /// </summary>
        internal static string TSQLSmell_RuleName02 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirty Reads cause consistency errors.
        /// </summary>
        internal static string TSQLSmell_RuleName03 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dont Override the optimizer.
        /// </summary>
        internal static string TSQLSmell_RuleName04 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid use of &apos;Select *&apos;.
        /// </summary>
        internal static string TSQLSmell_RuleName05 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid Explicit Conversion of Columnar data.
        /// </summary>
        internal static string TSQLSmell_RuleName06 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid use of ordinal positions in ORDER BY Clauses.
        /// </summary>
        internal static string TSQLSmell_RuleName07 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dont Change DateFormat.
        /// </summary>
        internal static string TSQLSmell_RuleName08 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dont Change DateFirst.
        /// </summary>
        internal static string TSQLSmell_RuleName09 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadUnCommitted: Dirty reads can cause consistency errors.
        /// </summary>
        internal static string TSQLSmell_RuleName10 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single character aliases are poor practice.
        /// </summary>
        internal static string TSQLSmell_RuleName11 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Column specifications on insert.
        /// </summary>
        internal static string TSQLSmell_RuleName12 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONCAT_NULL_YIELDS_NULL should be on.
        /// </summary>
        internal static string TSQLSmell_RuleName13 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANSI_NULLS should be On.
        /// </summary>
        internal static string TSQLSmell_RuleName14 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANSI_PADDING should be On.
        /// </summary>
        internal static string TSQLSmell_RuleName15 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANSI_WARNINGS should be On.
        /// </summary>
        internal static string TSQLSmell_RuleName16 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARITHABORT should be On.
        /// </summary>
        internal static string TSQLSmell_RuleName17 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUMERIC_ROUNDABORT should be Off.
        /// </summary>
        internal static string TSQLSmell_RuleName18 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUOTED_IDENTIFIER should be ON.
        /// </summary>
        internal static string TSQLSmell_RuleName19 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORCEPLAN should be OFF.
        /// </summary>
        internal static string TSQLSmell_RuleName20 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use 2 part naming in EXECUTE statements.
        /// </summary>
        internal static string TSQLSmell_RuleName21 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity value should be agnostic.
        /// </summary>
        internal static string TSQLSmell_RuleName22 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid single line comments.
        /// </summary>
        internal static string TSQLSmell_RuleName23 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use two part naming.
        /// </summary>
        internal static string TSQLSmell_RuleName24 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RANGE windows are much slower then ROWS (Explicit use).
        /// </summary>
        internal static string TSQLSmell_RuleName25 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RANGE windows are much slower then ROWS (Implicit use).
        /// </summary>
        internal static string TSQLSmell_RuleName26 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create table statements should specify schema.
        /// </summary>
        internal static string TSQLSmell_RuleName27 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordering in a view does not guarantee result set ordering.
        /// </summary>
        internal static string TSQLSmell_RuleName28 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursors default to writable.  Specify FAST_FORWARD.
        /// </summary>
        internal static string TSQLSmell_RuleName29 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include SET NOCOUNT ON inside stored procedures.
        /// </summary>
        internal static string TSQLSmell_RuleName30 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXISTS/NOT EXISTS can be more performant than COUNT(*).
        /// </summary>
        internal static string TSQLSmell_RuleName31 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordering in a derived table does not guarantee result set ordering.
        /// </summary>
        internal static string TSQLSmell_RuleName32 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single character variable names are poor practice.
        /// </summary>
        internal static string TSQLSmell_RuleName33 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression used with TOP should be wrapped in parenthises.
        /// </summary>
        internal static string TSQLSmell_RuleName34 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOP(100) percent is ignored by the optimizer.
        /// </summary>
        internal static string TSQLSmell_RuleName35 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign Key Constraints should be named.
        /// </summary>
        internal static string TSQLSmell_RuleName36 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Constraints should be named.
        /// </summary>
        internal static string TSQLSmell_RuleName37 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Key Constraints on temporary tables should not be named.
        /// </summary>
        internal static string TSQLSmell_RuleName38 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Constraints on temporary tables should not be named.
        /// </summary>
        internal static string TSQLSmell_RuleName39 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign Key Constraints on temporary tables should not be named.
        /// </summary>
        internal static string TSQLSmell_RuleName40 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Constraints on temporary tables should not be named.
        /// </summary>
        internal static string TSQLSmell_RuleName41 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use of SET ROWCOUNT is deprecated : use TOP.
        /// </summary>
        internal static string TSQLSmell_RuleName42 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potential SQL Injection Issue.
        /// </summary>
        internal static string TSQLSmell_RuleName43 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dont override the optimizer ( FORCESCAN ).
        /// </summary>
        internal static string TSQLSmell_RuleName44 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dont override the optimizer ( Index Hint).
        /// </summary>
        internal static string TSQLSmell_RuleName45 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;= Null&quot; Comparison.
        /// </summary>
        internal static string TSQLSmell_RuleName46 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use of deprecated data type.
        /// </summary>
        internal static string TSQLSmell_RuleName47 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSQLSmell_RuleName48.
        /// </summary>
        internal static string TSQLSmell_RuleName48 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSQLSmell_RuleName49.
        /// </summary>
        internal static string TSQLSmell_RuleName49 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSQLSmell_RuleName50.
        /// </summary>
        internal static string TSQLSmell_RuleName50 {
            get {
                return ResourceManager.GetString("TSQLSmell_RuleName50", resourceCulture);
            }
        }
    }
}
